#!/usr/bin/env bash

echo "----------------------------------------------------------------"
echo "----------------------------------------------------------------"
cat documentation.txt
echo "----------------------------------------------------------------"
echo "Running Make"
make
echo "----------------------------------------------------------------"
echo "Testing with No Command-line args"
./project1
echo "----------------------------------------------------------------"
echo "Testing with Correct SIC Assembly"
./project1 ../tests/test1.sic
echo "----------------------------------------------------------------"
echo "Testing case 2  SIC Program Has CLOOP defined twice"
./project1 ../tests/test2.sic
echo "----------------------------------------------------------------"
echo "Testing case 3  SIC Program Has Invalid Hex Constant"
./project1 ../tests/test3.sic
echo "----------------------------------------------------------------"
echo "Testing case 4  SIC Program Has Symbol Name that is an assembler Directive BYTE"
./project1 ../tests/test4.sic
echo "----------------------------------------------------------------"
echo "Testing case 5  SIC Program Starts at Hex 8000. No room left in SIC memory."
./project1 ../tests/test5.sic
echo "----------------------------------------------------------------"
echo "Testing case 6  Long Byte Constant that is ok. Has undefined symbol, Pass 1 should stop"
./project1 ../tests/test6.sic
echo "----------------------------------------------------------------"
echo "Testing case 7  Has blank lines - violates specification. Pass1 should stop"
./project1 ../tests/test7.sic
echo "----------------------------------------------------------------"
echo "Testing case 8 WORD Constant Exceeds 24 bit limitation"
./project1 ../tests/test8.sic
echo "----------------------------------------------------------------"
echo "Testing case 9 Program Has Invalid Symbol Name"
./project1 ../tests/test9.sic
echo "----------------------------------------------------------------"
echo "Testing case 10 Program Does not fit in SIC Memory"
./project1 ../tests/test10.sic
echo "----------------------------------------------------------------"
./project1 -a


